name: Build Stable Release

on:
  push:
    branches: [ custom-stable ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Build Firmware
        run: |
          docker run --rm -v "$PWD":/workspace -w /workspace espressif/idf:v5.3.1 bash -c "
            git config --global --add safe.directory /workspace &&
            idf.py set-target esp32s3 &&
            idf.py -D BOARD_TYPE=bread-compact-wifi-lcd build
          "
      - name: Upload Binaries
        uses: actions/upload-artifact@v4
        with:
          name: waveshare-stable-bin
          path: |
            build/bootloader/bootloader.bin
            build/partition_table/partition-table.bin
            build/xiaozhi.bin
