name: Build Waveshare Firmware

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: espressif/idf:v5.4
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build Firmware
        shell: bash
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          . /opt/esp/idf/export.sh
          idf.py set-target esp32s3
          idf.py -D BOARD_TYPE=bread-compact-wifi-lcd build

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: waveshare-binaries
          path: |
            build/bootloader/bootloader.bin
            build/partition_table/partition-table.bin
            build/xiaozhi.bin
