name: Build Custom Firmware

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: espressif/idf:release-v5.3
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build Firmware
        shell: bash
        run: |
          . $IDF_PATH/export.sh
          idf.py set-target esp32s3
          idf.py build

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: waveshare-firmware
          path: |
            build/bootloader/bootloader.bin
            build/partition_table/partition-table.bin
            build/xiaozhi.bin
            build/merged-binary.bin
